<?php
/**
 * This file is part of the "Docalist Core" plugin.
 *
 * Copyright (C) 2012, 2013 Daniel Ménard
 *
 * For copyright and license information, please view the
 * LICENSE.txt file that was distributed with this source code.
 *
 * @package     Docalist
 * @subpackage  Tables
 * @author      Daniel Ménard <daniel.menard@laposte.net>
 * @version     SVN: $Id$
 */

/*
 * Liste des pays, en français
 * Adapté de http://fr.wikipedia.org/wiki/ISO_3166-1
 *
 * 2013-04-09 Version initiale
 * 2013-09-27 Mise au format docalist. 249 pays.
 * 2013-11-03 Renomme 'alpha3' et 'name' en 'code' et 'label'.
 */

return [
    ['code', 'iso2', 'num', 'label'],

    ['ABW', 'AW', '533', __('Aruba', 'docalist-core')],
    ['AFG', 'AF', '004', __('Afghanistan', 'docalist-core')],
    ['AGO', 'AO', '024', __('Angola', 'docalist-core')],
    ['AIA', 'AI', '660', __('Anguilla', 'docalist-core')],
    ['ALA', 'AX', '248', __('Åland', 'docalist-core')],
    ['ALB', 'AL', '008', __('Albanie', 'docalist-core')],
    ['AND', 'AD', '020', __('Andorre', 'docalist-core')],
    ['ARE', 'AE', '784', __('Émirats arabes unis', 'docalist-core')],
    ['ARG', 'AR', '032', __('Argentine', 'docalist-core')],
    ['ARM', 'AM', '051', __('Arménie', 'docalist-core')],
    ['ASM', 'AS', '016', __('Samoa américaines', 'docalist-core')],
    ['ATA', 'AQ', '010', __('Antarctique', 'docalist-core')],
    ['ATF', 'TF', '260', __('Terres australes et antarctiques françaises', 'docalist-core')],
    ['ATG', 'AG', '028', __('Antigua-et-Barbuda', 'docalist-core')],
    ['AUS', 'AU', '036', __('Australie', 'docalist-core')],
    ['AUT', 'AT', '040', __('Autriche', 'docalist-core')],
    ['AZE', 'AZ', '031', __('Azerbaïdjan', 'docalist-core')],
    ['BDI', 'BI', '108', __('Burundi', 'docalist-core')],
    ['BEL', 'BE', '056', __('Belgique', 'docalist-core')],
    ['BEN', 'BJ', '204', __('Bénin', 'docalist-core')],
    ['BES', 'BQ', '535', __('Bonaire, Saint-Eustache et Saba', 'docalist-core')],
    ['BFA', 'BF', '854', __('Burkina Faso', 'docalist-core')],
    ['BGD', 'BD', '050', __('Bangladesh', 'docalist-core')],
    ['BGR', 'BG', '100', __('Bulgarie', 'docalist-core')],
    ['BHR', 'BH', '048', __('Bahreïn', 'docalist-core')],
    ['BHS', 'BS', '044', __('Bahamas', 'docalist-core')],
    ['BIH', 'BA', '070', __('Bosnie-Herzégovine', 'docalist-core')],
    ['BLM', 'BL', '652', __('Saint-Barthélemy', 'docalist-core')],
    ['BLR', 'BY', '112', __('Biélorussie', 'docalist-core')],
    ['BLZ', 'BZ', '084', __('Belize', 'docalist-core')],
    ['BMU', 'BM', '060', __('Bermudes', 'docalist-core')],
    ['BOL', 'BO', '068', __('Bolivie', 'docalist-core')],
    ['BRA', 'BR', '076', __('Brésil', 'docalist-core')],
    ['BRB', 'BB', '052', __('Barbade', 'docalist-core')],
    ['BRN', 'BN', '096', __('Brunei', 'docalist-core')],
    ['BTN', 'BT', '064', __('Bhoutan', 'docalist-core')],
    ['BVT', 'BV', '074', __('Île Bouvet', 'docalist-core')],
    ['BWA', 'BW', '072', __('Botswana', 'docalist-core')],
    ['CAF', 'CF', '140', __('République centrafricaine', 'docalist-core')],
    ['CAN', 'CA', '124', __('Canada', 'docalist-core')],
    ['CCK', 'CC', '166', __('Îles Cocos', 'docalist-core')],
    ['CHE', 'CH', '756', __('Suisse', 'docalist-core')],
    ['CHL', 'CL', '152', __('Chili', 'docalist-core')],
    ['CHN', 'CN', '156', __('Chine', 'docalist-core')],
    ['CIV', 'CI', '384', __('Côte d\'Ivoire', 'docalist-core')],
    ['CMR', 'CM', '120', __('Cameroun', 'docalist-core')],
    ['COD', 'CD', '180', __('République démocratique du Congo', 'docalist-core')],
    ['COG', 'CG', '178', __('République du Congo', 'docalist-core')],
    ['COK', 'CK', '184', __('Îles Cook', 'docalist-core')],
    ['COL', 'CO', '170', __('Colombie', 'docalist-core')],
    ['COM', 'KM', '174', __('Comores', 'docalist-core')],
    ['CPV', 'CV', '132', __('Cap-Vert', 'docalist-core')],
    ['CRI', 'CR', '188', __('Costa Rica', 'docalist-core')],
    ['CUB', 'CU', '192', __('Cuba', 'docalist-core')],
    ['CUW', 'CW', '531', __('Curaçao', 'docalist-core')],
    ['CXR', 'CX', '162', __('Île Christmas', 'docalist-core')],
    ['CYM', 'KY', '136', __('Îles Caïmans', 'docalist-core')],
    ['CYP', 'CY', '196', __('Chypre', 'docalist-core')],
    ['CZE', 'CZ', '203', __('République tchèque', 'docalist-core')],
    ['DEU', 'DE', '276', __('Allemagne', 'docalist-core')],
    ['DJI', 'DJ', '262', __('Djibouti', 'docalist-core')],
    ['DMA', 'DM', '212', __('Dominique', 'docalist-core')],
    ['DNK', 'DK', '208', __('Danemark', 'docalist-core')],
    ['DOM', 'DO', '214', __('République dominicaine', 'docalist-core')],
    ['DZA', 'DZ', '012', __('Algérie', 'docalist-core')],
    ['ECU', 'EC', '218', __('Équateur', 'docalist-core')],
    ['EGY', 'EG', '818', __('Égypte', 'docalist-core')],
    ['ERI', 'ER', '232', __('Érythrée', 'docalist-core')],
    ['ESH', 'EH', '732', __('Sahara occidental', 'docalist-core')],
    ['ESP', 'ES', '724', __('Espagne', 'docalist-core')],
    ['EST', 'EE', '233', __('Estonie', 'docalist-core')],
    ['ETH', 'ET', '231', __('Éthiopie', 'docalist-core')],
    ['FIN', 'FI', '246', __('Finlande', 'docalist-core')],
    ['FJI', 'FJ', '242', __('Fidji', 'docalist-core')],
    ['FLK', 'FK', '238', __('Îles Malouines', 'docalist-core')],
    ['FRA', 'FR', '250', __('France', 'docalist-core')],
    ['FRO', 'FO', '234', __('Îles Féroé', 'docalist-core')],
    ['FSM', 'FM', '583', __('Micronésie', 'docalist-core')],
    ['GAB', 'GA', '266', __('Gabon', 'docalist-core')],
    ['GBR', 'GB', '826', __('Royaume-Uni', 'docalist-core')],
    ['GEO', 'GE', '268', __('Géorgie', 'docalist-core')],
    ['GGY', 'GG', '831', __('Guernesey', 'docalist-core')],
    ['GHA', 'GH', '288', __('Ghana', 'docalist-core')],
    ['GIB', 'GI', '292', __('Gibraltar', 'docalist-core')],
    ['GIN', 'GN', '324', __('Guinée', 'docalist-core')],
    ['GLP', 'GP', '312', __('Guadeloupe', 'docalist-core')],
    ['GMB', 'GM', '270', __('Gambie', 'docalist-core')],
    ['GNB', 'GW', '624', __('Guinée-Bissau', 'docalist-core')],
    ['GNQ', 'GQ', '226', __('Guinée équatoriale', 'docalist-core')],
    ['GRC', 'GR', '300', __('Grèce', 'docalist-core')],
    ['GRD', 'GD', '308', __('Grenade', 'docalist-core')],
    ['GRL', 'GL', '304', __('Groenland', 'docalist-core')],
    ['GTM', 'GT', '320', __('Guatemala', 'docalist-core')],
    ['GUF', 'GF', '254', __('Guyane', 'docalist-core')],
    ['GUM', 'GU', '316', __('Guam', 'docalist-core')],
    ['GUY', 'GY', '328', __('Guyana', 'docalist-core')],
    ['HKG', 'HK', '344', __('Hong Kong', 'docalist-core')],
    ['HMD', 'HM', '334', __('Îles Heard-et-MacDonald', 'docalist-core')],
    ['HND', 'HN', '340', __('Honduras', 'docalist-core')],
    ['HRV', 'HR', '191', __('Croatie', 'docalist-core')],
    ['HTI', 'HT', '332', __('Haïti', 'docalist-core')],
    ['HUN', 'HU', '348', __('Hongrie', 'docalist-core')],
    ['IDN', 'ID', '360', __('Indonésie', 'docalist-core')],
    ['IMN', 'IM', '833', __('Île de Man', 'docalist-core')],
    ['IND', 'IN', '356', __('Inde', 'docalist-core')],
    ['IOT', 'IO', '086', __('Territoire britannique de l\'océan Indien', 'docalist-core')],
    ['IRL', 'IE', '372', __('Irlande', 'docalist-core')],
    ['IRN', 'IR', '364', __('Iran', 'docalist-core')],
    ['IRQ', 'IQ', '368', __('Irak', 'docalist-core')],
    ['ISL', 'IS', '352', __('Islande', 'docalist-core')],
    ['ISR', 'IL', '376', __('Israël', 'docalist-core')],
    ['ITA', 'IT', '380', __('Italie', 'docalist-core')],
    ['JAM', 'JM', '388', __('Jamaïque', 'docalist-core')],
    ['JEY', 'JE', '832', __('Jersey', 'docalist-core')],
    ['JOR', 'JO', '400', __('Jordanie', 'docalist-core')],
    ['JPN', 'JP', '392', __('Japon', 'docalist-core')],
    ['KAZ', 'KZ', '398', __('Kazakhstan', 'docalist-core')],
    ['KEN', 'KE', '404', __('Kenya', 'docalist-core')],
    ['KGZ', 'KG', '417', __('Kirghizistan', 'docalist-core')],
    ['KHM', 'KH', '116', __('Cambodge', 'docalist-core')],
    ['KIR', 'KI', '296', __('Kiribati', 'docalist-core')],
    ['KNA', 'KN', '659', __('Saint-Christophe-et-Niévès', 'docalist-core')],
    ['KOR', 'KR', '410', __('Corée du Sud', 'docalist-core')],
    ['KWT', 'KW', '414', __('Koweït', 'docalist-core')],
    ['LAO', 'LA', '418', __('Laos', 'docalist-core')],
    ['LBN', 'LB', '422', __('Liban', 'docalist-core')],
    ['LBR', 'LR', '430', __('Liberia', 'docalist-core')],
    ['LBY', 'LY', '434', __('Libye', 'docalist-core')],
    ['LCA', 'LC', '662', __('Sainte-Lucie', 'docalist-core')],
    ['LIE', 'LI', '438', __('Liechtenstein', 'docalist-core')],
    ['LKA', 'LK', '144', __('Sri Lanka', 'docalist-core')],
    ['LSO', 'LS', '426', __('Lesotho', 'docalist-core')],
    ['LTU', 'LT', '440', __('Lituanie', 'docalist-core')],
    ['LUX', 'LU', '442', __('Luxembourg', 'docalist-core')],
    ['LVA', 'LV', '428', __('Lettonie', 'docalist-core')],
    ['MAC', 'MO', '446', __('Macao', 'docalist-core')],
    ['MAF', 'MF', '663', __('Saint-Martin', 'docalist-core')],
    ['MAR', 'MA', '504', __('Maroc', 'docalist-core')],
    ['MCO', 'MC', '492', __('Monaco', 'docalist-core')],
    ['MDA', 'MD', '498', __('Moldavie', 'docalist-core')],
    ['MDG', 'MG', '450', __('Madagascar', 'docalist-core')],
    ['MDV', 'MV', '462', __('Maldives', 'docalist-core')],
    ['MEX', 'MX', '484', __('Mexique', 'docalist-core')],
    ['MHL', 'MH', '584', __('Marshall', 'docalist-core')],
    ['MKD', 'MK', '807', __('Macédoine', 'docalist-core')],
    ['MLI', 'ML', '466', __('Mali', 'docalist-core')],
    ['MLT', 'MT', '470', __('Malte', 'docalist-core')],
    ['MMR', 'MM', '104', __('Birmanie', 'docalist-core')],
    ['MNE', 'ME', '499', __('Monténégro', 'docalist-core')],
    ['MNG', 'MN', '496', __('Mongolie', 'docalist-core')],
    ['MNP', 'MP', '580', __('Îles Mariannes du Nord', 'docalist-core')],
    ['MOZ', 'MZ', '508', __('Mozambique', 'docalist-core')],
    ['MRT', 'MR', '478', __('Mauritanie', 'docalist-core')],
    ['MSR', 'MS', '500', __('Montserrat', 'docalist-core')],
    ['MTQ', 'MQ', '474', __('Martinique', 'docalist-core')],
    ['MUS', 'MU', '480', __('Maurice', 'docalist-core')],
    ['MWI', 'MW', '454', __('Malawi', 'docalist-core')],
    ['MYS', 'MY', '458', __('Malaisie', 'docalist-core')],
    ['MYT', 'YT', '175', __('Mayotte', 'docalist-core')],
    ['NAM', 'NA', '516', __('Namibie', 'docalist-core')],
    ['NCL', 'NC', '540', __('Nouvelle-Calédonie', 'docalist-core')],
    ['NER', 'NE', '562', __('Niger', 'docalist-core')],
    ['NFK', 'NF', '574', __('Île Norfolk', 'docalist-core')],
    ['NGA', 'NG', '566', __('Nigeria', 'docalist-core')],
    ['NIC', 'NI', '558', __('Nicaragua', 'docalist-core')],
    ['NIU', 'NU', '570', __('Niue', 'docalist-core')],
    ['NLD', 'NL', '528', __('Pays-Bas', 'docalist-core')],
    ['NOR', 'NO', '578', __('Norvège', 'docalist-core')],
    ['NPL', 'NP', '524', __('Népal', 'docalist-core')],
    ['NRU', 'NR', '520', __('Nauru', 'docalist-core')],
    ['NZL', 'NZ', '554', __('Nouvelle-Zélande', 'docalist-core')],
    ['OMN', 'OM', '512', __('Oman', 'docalist-core')],
    ['PAK', 'PK', '586', __('Pakistan', 'docalist-core')],
    ['PAN', 'PA', '591', __('Panama', 'docalist-core')],
    ['PCN', 'PN', '612', __('Îles Pitcairn', 'docalist-core')],
    ['PER', 'PE', '604', __('Pérou', 'docalist-core')],
    ['PHL', 'PH', '608', __('Philippines', 'docalist-core')],
    ['PLW', 'PW', '585', __('Palaos', 'docalist-core')],
    ['PNG', 'PG', '598', __('Papouasie-Nouvelle-Guinée', 'docalist-core')],
    ['POL', 'PL', '616', __('Pologne', 'docalist-core')],
    ['PRI', 'PR', '630', __('Porto Rico', 'docalist-core')],
    ['PRK', 'KP', '408', __('Corée du Nord', 'docalist-core')],
    ['PRT', 'PT', '620', __('Portugal', 'docalist-core')],
    ['PRY', 'PY', '600', __('Paraguay', 'docalist-core')],
    ['PSE', 'PS', '275', __('Palestine', 'docalist-core')],
    ['PYF', 'PF', '258', __('Polynésie française', 'docalist-core')],
    ['QAT', 'QA', '634', __('Qatar', 'docalist-core')],
    ['REU', 'RE', '638', __('La Réunion', 'docalist-core')],
    ['ROU', 'RO', '642', __('Roumanie', 'docalist-core')],
    ['RUS', 'RU', '643', __('Russie', 'docalist-core')],
    ['RWA', 'RW', '646', __('Rwanda', 'docalist-core')],
    ['SAU', 'SA', '682', __('Arabie saoudite', 'docalist-core')],
    ['SDN', 'SD', '729', __('Soudan', 'docalist-core')],
    ['SEN', 'SN', '686', __('Sénégal', 'docalist-core')],
    ['SGP', 'SG', '702', __('Singapour', 'docalist-core')],
    ['SGS', 'GS', '239', __('Géorgie du Sud-et-les Îles Sandwich du Sud', 'docalist-core')],
    ['SHN', 'SH', '654', __('Sainte-Hélène, Ascension et Tristan da Cunha|', 'docalist-core')],
    ['SJM', 'SJ', '744', __('Svalbard et île Jan Mayen', 'docalist-core')],
    ['SLB', 'SB', '090', __('Salomon', 'docalist-core')],
    ['SLE', 'SL', '694', __('Sierra Leone', 'docalist-core')],
    ['SLV', 'SV', '222', __('Salvador', 'docalist-core')],
    ['SMR', 'SM', '674', __('Saint-Marin', 'docalist-core')],
    ['SOM', 'SO', '706', __('Somalie', 'docalist-core')],
    ['SPM', 'PM', '666', __('Saint-Pierre-et-Miquelon', 'docalist-core')],
    ['SRB', 'RS', '688', __('Serbie', 'docalist-core')],
    ['SSD', 'SS', '728', __('Soudan du Sud', 'docalist-core')],
    ['STP', 'ST', '678', __('Sao Tomé-et-Principe', 'docalist-core')],
    ['SUR', 'SR', '740', __('Suriname', 'docalist-core')],
    ['SVK', 'SK', '703', __('Slovaquie', 'docalist-core')],
    ['SVN', 'SI', '705', __('Slovénie', 'docalist-core')],
    ['SWE', 'SE', '752', __('Suède', 'docalist-core')],
    ['SWZ', 'SZ', '748', __('Swaziland', 'docalist-core')],
    ['SXM', 'SX', '534', __('Saint-Martin', 'docalist-core')],
    ['SYC', 'SC', '690', __('Seychelles', 'docalist-core')],
    ['SYR', 'SY', '760', __('Syrie', 'docalist-core')],
    ['TCA', 'TC', '796', __('Îles Turques-et-Caïques', 'docalist-core')],
    ['TCD', 'TD', '148', __('Tchad', 'docalist-core')],
    ['TGO', 'TG', '768', __('Togo', 'docalist-core')],
    ['THA', 'TH', '764', __('Thaïlande', 'docalist-core')],
    ['TJK', 'TJ', '762', __('Tadjikistan', 'docalist-core')],
    ['TKL', 'TK', '772', __('Tokelau', 'docalist-core')],
    ['TKM', 'TM', '795', __('Turkménistan', 'docalist-core')],
    ['TLS', 'TL', '626', __('Timor oriental', 'docalist-core')],
    ['TON', 'TO', '776', __('Tonga', 'docalist-core')],
    ['TTO', 'TT', '780', __('Trinité-et-Tobago', 'docalist-core')],
    ['TUN', 'TN', '788', __('Tunisie', 'docalist-core')],
    ['TUR', 'TR', '792', __('Turquie', 'docalist-core')],
    ['TUV', 'TV', '798', __('Tuvalu', 'docalist-core')],
    ['TWN', 'TW', '158', __('Taïwan', 'docalist-core')],
    ['TZA', 'TZ', '834', __('Tanzanie', 'docalist-core')],
    ['UGA', 'UG', '800', __('Ouganda', 'docalist-core')],
    ['UKR', 'UA', '804', __('Ukraine', 'docalist-core')],
    ['UMI', 'UM', '581', __('Îles mineures éloignées des États-Unis', 'docalist-core')],
    ['URY', 'UY', '858', __('Uruguay', 'docalist-core')],
    ['USA', 'US', '840', __('États-Unis', 'docalist-core')],
    ['UZB', 'UZ', '860', __('Ouzbékistan', 'docalist-core')],
    ['VAT', 'VA', '336', __('Vatican', 'docalist-core')],
    ['VCT', 'VC', '670', __('Saint-Vincent-et-les-Grenadines', 'docalist-core')],
    ['VEN', 'VE', '862', __('Venezuela', 'docalist-core')],
    ['VGB', 'VG', '092', __('Îles Vierges britanniques', 'docalist-core')],
    ['VIR', 'VI', '850', __('Îles Vierges des États-Unis', 'docalist-core')],
    ['VNM', 'VN', '704', __('Viêt Nam', 'docalist-core')],
    ['VUT', 'VU', '548', __('Vanuatu', 'docalist-core')],
    ['WLF', 'WF', '876', __('Wallis-et-Futuna', 'docalist-core')],
    ['WSM', 'WS', '882', __('Samoa', 'docalist-core')],
    ['YEM', 'YE', '887', __('Yémen', 'docalist-core')],
    ['ZAF', 'ZA', '710', __('Afrique du Sud', 'docalist-core')],
    ['ZMB', 'ZM', '894', __('Zambie', 'docalist-core')],
    ['ZWE', 'ZW', '716', __('Zimbabwe', 'docalist-core')],
];