<?php
/**
 * This file is part of the "Docalist Core" plugin.
 *
 * Copyright (C) 2012, 2013 Daniel Ménard
 *
 * For copyright and license information, please view the
 * LICENSE.txt file that was distributed with this source code.
 *
 * @package     Docalist
 * @subpackage  Tables
 * @author      Daniel Ménard <daniel.menard@laposte.net>
 * @version     SVN: $Id$
 */

/*
 * Liste des langues, en français
 * Adapté de http://www.loc.gov/standards/iso639-2/php/French_list.php
 *
 * 2013-04-09 Version initiale
 * 2013-09-27 Mise au format docalist. 538 langues.
 */

return [
    ['code', 'alpha2', __('label', 'docalist-core')],

    ['aar', 'aa', __('afar', 'docalist-core')],
    ['abk', 'ab', __('abkhaze', 'docalist-core')],
    ['ace', '', __('aceh', 'docalist-core')],
    ['ach', '', __('acoli', 'docalist-core')],
    ['ada', '', __('adangme', 'docalist-core')],
    ['ady', '', __('adyghé', 'docalist-core')],
    ['afa', '', __('afro-asiatiques, langues', 'docalist-core')],
    ['afh', '', __('afrihili', 'docalist-core')],
    ['afr', 'af', __('afrikaans', 'docalist-core')],
    ['ain', '', __('aïnou', 'docalist-core')],
    ['aka', 'ak', __('akan', 'docalist-core')],
    ['akk', '', __('akkadien', 'docalist-core')],
    ['alb', 'sq', __('albanais', 'docalist-core')],
    ['ale', '', __('aléoute', 'docalist-core')],
    ['alg', '', __('algonquines, langues', 'docalist-core')],
    ['alt', '', __('altai du Sud', 'docalist-core')],
    ['amh', 'am', __('amharique', 'docalist-core')],
    ['ang', '', __('anglo-saxon (ca.450-1100)', 'docalist-core')],
    ['anp', '', __('angika', 'docalist-core')],
    ['apa', '', __('apaches, langues', 'docalist-core')],
    ['ara', 'ar', __('arabe', 'docalist-core')],
    ['arc', '', __('araméen d\'empire (700-300 BCE)', 'docalist-core')],
    ['arg', 'an', __('aragonais', 'docalist-core')],
    ['arm', 'hy', __('arménien', 'docalist-core')],
    ['arn', '', __('mapuce', 'docalist-core')],
    ['arn', '', __('mapuche', 'docalist-core')],
    ['arn', '', __('mapudungun', 'docalist-core')],
    ['arp', '', __('arapaho', 'docalist-core')],
    ['art', '', __('artificielles, langues', 'docalist-core')],
    ['arw', '', __('arawak', 'docalist-core')],
    ['asm', 'as', __('assamais', 'docalist-core')],
    ['ast', '', __('asturien', 'docalist-core')],
    ['ast', '', __('asturoléonais', 'docalist-core')],
    ['ast', '', __('bable', 'docalist-core')],
    ['ast', '', __('léonais', 'docalist-core')],
    ['ath', '', __('athapascanes, langues', 'docalist-core')],
    ['aus', '', __('australiennes, langues', 'docalist-core')],
    ['ava', 'av', __('avar', 'docalist-core')],
    ['ave', 'ae', __('avestique', 'docalist-core')],
    ['awa', '', __('awadhi', 'docalist-core')],
    ['aym', 'ay', __('aymara', 'docalist-core')],
    ['aze', 'az', __('azéri', 'docalist-core')],
    ['bad', '', __('banda, langues', 'docalist-core')],
    ['bai', '', __('bamiléké, langues', 'docalist-core')],
    ['bak', 'ba', __('bachkir', 'docalist-core')],
    ['bal', '', __('baloutchi', 'docalist-core')],
    ['bam', 'bm', __('bambara', 'docalist-core')],
    ['ban', '', __('balinais', 'docalist-core')],
    ['baq', 'eu', __('basque', 'docalist-core')],
    ['bas', '', __('basa', 'docalist-core')],
    ['bat', '', __('baltes, langues', 'docalist-core')],
    ['bej', '', __('bedja', 'docalist-core')],
    ['bel', 'be', __('biélorusse', 'docalist-core')],
    ['bem', '', __('bemba', 'docalist-core')],
    ['ben', 'bn', __('bengali', 'docalist-core')],
    ['ber', '', __('berbères, langues', 'docalist-core')],
    ['bho', '', __('bhojpuri', 'docalist-core')],
    ['bih', 'bh', __('langues biharis', 'docalist-core')],
    ['bik', '', __('bikol', 'docalist-core')],
    ['bin', '', __('bini', 'docalist-core')],
    ['bin', '', __('edo', 'docalist-core')],
    ['bis', 'bi', __('bichlamar', 'docalist-core')],
    ['bla', '', __('blackfoot', 'docalist-core')],
    ['bnt', '', __('bantou, langues', 'docalist-core')],
    ['bos', 'bs', __('bosniaque', 'docalist-core')],
    ['bra', '', __('braj', 'docalist-core')],
    ['bre', 'br', __('breton', 'docalist-core')],
    ['btk', '', __('batak, langues', 'docalist-core')],
    ['bua', '', __('bouriate', 'docalist-core')],
    ['bug', '', __('bugi', 'docalist-core')],
    ['bul', 'bg', __('bulgare', 'docalist-core')],
    ['bur', 'my', __('birman', 'docalist-core')],
    ['byn', '', __('bilen', 'docalist-core')],
    ['byn', '', __('blin', 'docalist-core')],
    ['cad', '', __('caddo', 'docalist-core')],
    ['cai', '', __('amérindiennes de l\'Amérique centrale, langues', 'docalist-core')],
    ['car', '', __('carib', 'docalist-core')],
    ['car', '', __('galibi', 'docalist-core')],
    ['car', '', __('karib', 'docalist-core')],
    ['cat', 'ca', __('catalan', 'docalist-core')],
    ['cat', 'ca', __('valencien', 'docalist-core')],
    ['cau', '', __('caucasiennes, langues', 'docalist-core')],
    ['ceb', '', __('cebuano', 'docalist-core')],
    ['cel', '', __('celtes, langues', 'docalist-core')],
    ['cel', '', __('celtiques, langues', 'docalist-core')],
    ['cha', 'ch', __('chamorro', 'docalist-core')],
    ['chb', '', __('chibcha', 'docalist-core')],
    ['che', 'ce', __('tchétchène', 'docalist-core')],
    ['chg', '', __('djaghataï', 'docalist-core')],
    ['chi', 'zh', __('chinois', 'docalist-core')],
    ['chk', '', __('chuuk', 'docalist-core')],
    ['chm', '', __('mari', 'docalist-core')],
    ['chn', '', __('chinook, jargon', 'docalist-core')],
    ['cho', '', __('choctaw', 'docalist-core')],
    ['chp', '', __('chipewyan', 'docalist-core')],
    ['chr', '', __('cherokee', 'docalist-core')],
    ['chu', 'cu', __('slavon d\'église', 'docalist-core')],
    ['chu', 'cu', __('slavon liturgique', 'docalist-core')],
    ['chu', 'cu', __('vieux bulgare', 'docalist-core')],
    ['chu', 'cu', __('vieux slave', 'docalist-core')],
    ['chv', 'cv', __('tchouvache', 'docalist-core')],
    ['chy', '', __('cheyenne', 'docalist-core')],
    ['cmc', '', __('chames, langues', 'docalist-core')],
    ['cop', '', __('copte', 'docalist-core')],
    ['cor', 'kw', __('cornique', 'docalist-core')],
    ['cos', 'co', __('corse', 'docalist-core')],
    ['cpe', '', __('créoles et pidgins basés sur l\'anglais', 'docalist-core')],
    ['cpf', '', __('créoles et pidgins basés sur le français', 'docalist-core')],
    ['cpp', '', __('créoles et pidgins basés sur le portugais', 'docalist-core')],
    ['cre', 'cr', __('cree', 'docalist-core')],
    ['crh', '', __('tatar de Crimé', 'docalist-core')],
    ['crp', '', __('créoles et pidgins', 'docalist-core')],
    ['csb', '', __('kachoube', 'docalist-core')],
    ['cus', '', __('couchitiques, langues', 'docalist-core')],
    ['cze', 'cs', __('tchèque', 'docalist-core')],
    ['dak', '', __('dakota', 'docalist-core')],
    ['dan', 'da', __('danois', 'docalist-core')],
    ['dar', '', __('dargwa', 'docalist-core')],
    ['day', '', __('dayak, langues', 'docalist-core')],
    ['del', '', __('delaware', 'docalist-core')],
    ['den', '', __('esclave (athapascan)', 'docalist-core')],
    ['dgr', '', __('dogrib', 'docalist-core')],
    ['din', '', __('dinka', 'docalist-core')],
    ['div', 'dv', __('maldivien', 'docalist-core')],
    ['doi', '', __('dogri', 'docalist-core')],
    ['dra', '', __('dravidiennes, langues', 'docalist-core')],
    ['dsb', '', __('bas-sorabe', 'docalist-core')],
    ['dua', '', __('douala', 'docalist-core')],
    ['dum', '', __('néerlandais moyen (ca. 1050-1350)', 'docalist-core')],
    ['dut', 'nl', __('flamand', 'docalist-core')],
    ['dut', 'nl', __('néerlandais', 'docalist-core')],
    ['dyu', '', __('dioula', 'docalist-core')],
    ['dzo', 'dz', __('dzongkha', 'docalist-core')],
    ['efi', '', __('efik', 'docalist-core')],
    ['egy', '', __('égyptien', 'docalist-core')],
    ['eka', '', __('ekajuk', 'docalist-core')],
    ['elx', '', __('élamite', 'docalist-core')],
    ['eng', 'en', __('anglais', 'docalist-core')],
    ['enm', '', __('anglais moyen (1100-1500)', 'docalist-core')],
    ['epo', 'eo', __('espéranto', 'docalist-core')],
    ['est', 'et', __('estonien', 'docalist-core')],
    ['ewe', 'ee', __('éwé', 'docalist-core')],
    ['ewo', '', __('éwondo', 'docalist-core')],
    ['fan', '', __('fang', 'docalist-core')],
    ['fao', 'fo', __('féroïen', 'docalist-core')],
    ['fat', '', __('fanti', 'docalist-core')],
    ['fij', 'fj', __('fidjien', 'docalist-core')],
    ['fil', '', __('filipino', 'docalist-core')],
    ['fil', '', __('pilipino', 'docalist-core')],
    ['fin', 'fi', __('finnois', 'docalist-core')],
    ['fiu', '', __('finno-ougriennes, langues', 'docalist-core')],
    ['fon', '', __('fon', 'docalist-core')],
    ['fre', 'fr', __('français', 'docalist-core')],
    ['frm', '', __('français moyen (1400-1600)', 'docalist-core')],
    ['fro', '', __('français ancien (842-ca.1400)', 'docalist-core')],
    ['frr', '', __('frison septentrional', 'docalist-core')],
    ['frs', '', __('frison oriental', 'docalist-core')],
    ['fry', 'fy', __('frison occidental', 'docalist-core')],
    ['ful', 'ff', __('peul', 'docalist-core')],
    ['fur', '', __('frioulan', 'docalist-core')],
    ['gaa', '', __('ga', 'docalist-core')],
    ['gay', '', __('gayo', 'docalist-core')],
    ['gba', '', __('gbaya', 'docalist-core')],
    ['gem', '', __('germaniques, langues', 'docalist-core')],
    ['geo', 'ka', __('géorgien', 'docalist-core')],
    ['ger', 'de', __('allemand', 'docalist-core')],
    ['gez', '', __('guèze', 'docalist-core')],
    ['gil', '', __('kiribati', 'docalist-core')],
    ['gla', 'gd', __('gaélique', 'docalist-core')],
    ['gla', 'gd', __('gaélique écossais', 'docalist-core')],
    ['gle', 'ga', __('irlandais', 'docalist-core')],
    ['glg', 'gl', __('galicien', 'docalist-core')],
    ['glv', 'gv', __('mannois', 'docalist-core')],
    ['glv', 'gv', __('manx', 'docalist-core')],
    ['gmh', '', __('allemand, moyen haut (ca. 1050-1500)', 'docalist-core')],
    ['goh', '', __('allemand, vieux haut (ca. 750-1050)', 'docalist-core')],
    ['gon', '', __('gond', 'docalist-core')],
    ['gor', '', __('gorontalo', 'docalist-core')],
    ['got', '', __('gothique', 'docalist-core')],
    ['grb', '', __('grebo', 'docalist-core')],
    ['grc', '', __('grec ancien (jusqu\'à 1453)', 'docalist-core')],
    ['gre', 'el', __('grec moderne (après 1453)', 'docalist-core')],
    ['grn', 'gn', __('guarani', 'docalist-core')],
    ['gsw', '', __('alémanique', 'docalist-core')],
    ['gsw', '', __('alsacien', 'docalist-core')],
    ['gsw', '', __('suisse alémanique', 'docalist-core')],
    ['guj', 'gu', __('goudjrati', 'docalist-core')],
    ['gwi', '', __('gwich\'in', 'docalist-core')],
    ['hai', '', __('haida', 'docalist-core')],
    ['hat', 'ht', __('créole haïtien', 'docalist-core')],
    ['hat', 'ht', __('haïtien', 'docalist-core')],
    ['hau', 'ha', __('haoussa', 'docalist-core')],
    ['haw', '', __('hawaïen', 'docalist-core')],
    ['heb', 'he', __('hébreu', 'docalist-core')],
    ['her', 'hz', __('herero', 'docalist-core')],
    ['hil', '', __('hiligaynon', 'docalist-core')],
    ['him', '', __('langues himachalis', 'docalist-core')],
    ['him', '', __('langues paharis occidentales', 'docalist-core')],
    ['hin', 'hi', __('hindi', 'docalist-core')],
    ['hit', '', __('hittite', 'docalist-core')],
    ['hmn', '', __('hmong', 'docalist-core')],
    ['hmo', 'ho', __('hiri motu', 'docalist-core')],
    ['hrv', 'hr', __('croate', 'docalist-core')],
    ['hsb', '', __('haut-sorabe', 'docalist-core')],
    ['hun', 'hu', __('hongrois', 'docalist-core')],
    ['hup', '', __('hupa', 'docalist-core')],
    ['iba', '', __('iban', 'docalist-core')],
    ['ibo', 'ig', __('igbo', 'docalist-core')],
    ['ice', 'is', __('islandais', 'docalist-core')],
    ['ido', 'io', __('ido', 'docalist-core')],
    ['iii', 'ii', __('yi de Sichuan', 'docalist-core')],
    ['ijo', '', __('ijo, langues', 'docalist-core')],
    ['iku', 'iu', __('inuktitut', 'docalist-core')],
    ['ile', 'ie', __('interlingue', 'docalist-core')],
    ['ilo', '', __('ilocano', 'docalist-core')],
    ['ina', 'ia', __('interlingua (langue auxiliaire internationale)', 'docalist-core')],
    ['inc', '', __('indo-aryennes, langues', 'docalist-core')],
    ['ind', 'id', __('indonésien', 'docalist-core')],
    ['ine', '', __('indo-européennes, langues', 'docalist-core')],
    ['inh', '', __('ingouche', 'docalist-core')],
    ['ipk', 'ik', __('inupiaq', 'docalist-core')],
    ['ira', '', __('iraniennes, langues', 'docalist-core')],
    ['iro', '', __('iroquoises, langues', 'docalist-core')],
    ['ita', 'it', __('italien', 'docalist-core')],
    ['jav', 'jv', __('javanais', 'docalist-core')],
    ['jbo', '', __('lojban', 'docalist-core')],
    ['jpn', 'ja', __('japonais', 'docalist-core')],
    ['jpr', '', __('judéo-persan', 'docalist-core')],
    ['jrb', '', __('judéo-arabe', 'docalist-core')],
    ['kaa', '', __('karakalpak', 'docalist-core')],
    ['kab', '', __('kabyle', 'docalist-core')],
    ['kac', '', __('jingpho', 'docalist-core')],
    ['kac', '', __('kachin', 'docalist-core')],
    ['kal', 'kl', __('groenlandais', 'docalist-core')],
    ['kam', '', __('kamba', 'docalist-core')],
    ['kan', 'kn', __('kannada', 'docalist-core')],
    ['kar', '', __('karen, langues', 'docalist-core')],
    ['kas', 'ks', __('kashmiri', 'docalist-core')],
    ['kau', 'kr', __('kanouri', 'docalist-core')],
    ['kaw', '', __('kawi', 'docalist-core')],
    ['kaz', 'kk', __('kazakh', 'docalist-core')],
    ['kbd', '', __('kabardien', 'docalist-core')],
    ['kha', '', __('khasi', 'docalist-core')],
    ['khi', '', __('khoïsan, langues', 'docalist-core')],
    ['khm', 'km', __('khmer central', 'docalist-core')],
    ['kho', '', __('khotanais', 'docalist-core')],
    ['kho', '', __('sakan', 'docalist-core')],
    ['kik', 'ki', __('kikuyu', 'docalist-core')],
    ['kin', 'rw', __('rwanda', 'docalist-core')],
    ['kir', 'ky', __('kirghiz', 'docalist-core')],
    ['kmb', '', __('kimbundu', 'docalist-core')],
    ['kok', '', __('konkani', 'docalist-core')],
    ['kom', 'kv', __('kom', 'docalist-core')],
    ['kon', 'kg', __('kongo', 'docalist-core')],
    ['kor', 'ko', __('coréen', 'docalist-core')],
    ['kos', '', __('kosrae', 'docalist-core')],
    ['kpe', '', __('kpellé', 'docalist-core')],
    ['krc', '', __('karatchai balkar', 'docalist-core')],
    ['krl', '', __('carélien', 'docalist-core')],
    ['kro', '', __('krou, langues', 'docalist-core')],
    ['kru', '', __('kurukh', 'docalist-core')],
    ['kua', 'kj', __('kuanyama', 'docalist-core')],
    ['kua', 'kj', __('kwanyama', 'docalist-core')],
    ['kum', '', __('koumyk', 'docalist-core')],
    ['kur', 'ku', __('kurde', 'docalist-core')],
    ['kut', '', __('kutenai', 'docalist-core')],
    ['lad', '', __('judéo-espagnol', 'docalist-core')],
    ['lah', '', __('lahnda', 'docalist-core')],
    ['lam', '', __('lamba', 'docalist-core')],
    ['lao', 'lo', __('lao', 'docalist-core')],
    ['lat', 'la', __('latin', 'docalist-core')],
    ['lav', 'lv', __('letton', 'docalist-core')],
    ['lez', '', __('lezghien', 'docalist-core')],
    ['lim', 'li', __('limbourgeois', 'docalist-core')],
    ['lin', 'ln', __('lingala', 'docalist-core')],
    ['lit', 'lt', __('lituanien', 'docalist-core')],
    ['lol', '', __('mongo', 'docalist-core')],
    ['loz', '', __('lozi', 'docalist-core')],
    ['ltz', 'lb', __('luxembourgeois', 'docalist-core')],
    ['lua', '', __('luba-lulua', 'docalist-core')],
    ['lub', 'lu', __('luba-katanga', 'docalist-core')],
    ['lug', 'lg', __('ganda', 'docalist-core')],
    ['lui', '', __('luiseno', 'docalist-core')],
    ['lun', '', __('lunda', 'docalist-core')],
    ['luo', '', __('luo (Kenya et Tanzanie)', 'docalist-core')],
    ['lus', '', __('Lushai', 'docalist-core')],
    ['mac', 'mk', __('macédonien', 'docalist-core')],
    ['mad', '', __('madourais', 'docalist-core')],
    ['mag', '', __('magahi', 'docalist-core')],
    ['mah', 'mh', __('marshall', 'docalist-core')],
    ['mai', '', __('maithili', 'docalist-core')],
    ['mak', '', __('makassar', 'docalist-core')],
    ['mal', 'ml', __('malayalam', 'docalist-core')],
    ['man', '', __('mandingue', 'docalist-core')],
    ['mao', 'mi', __('maori', 'docalist-core')],
    ['map', '', __('austronésiennes, langues', 'docalist-core')],
    ['mar', 'mr', __('marathe', 'docalist-core')],
    ['mas', '', __('massaï', 'docalist-core')],
    ['may', 'ms', __('malais', 'docalist-core')],
    ['mdf', '', __('moksa', 'docalist-core')],
    ['mdr', '', __('mandar', 'docalist-core')],
    ['men', '', __('mendé', 'docalist-core')],
    ['mga', '', __('irlandais moyen (900-1200)', 'docalist-core')],
    ['mic', '', __('mi\'kmaq', 'docalist-core')],
    ['mic', '', __('micmac', 'docalist-core')],
    ['min', '', __('minangkabau', 'docalist-core')],
    ['mis', '', __('langues non codées', 'docalist-core')],
    ['mkh', '', __('môn-khmer, langues', 'docalist-core')],
    ['mlg', 'mg', __('malgache', 'docalist-core')],
    ['mlt', 'mt', __('maltais', 'docalist-core')],
    ['mnc', '', __('mandchou', 'docalist-core')],
    ['mni', '', __('manipuri', 'docalist-core')],
    ['mno', '', __('manobo, langues', 'docalist-core')],
    ['moh', '', __('mohawk', 'docalist-core')],
    ['mon', 'mn', __('mongol', 'docalist-core')],
    ['mos', '', __('moré', 'docalist-core')],
    ['mul', '', __('multilingue', 'docalist-core')],
    ['mun', '', __('mounda, langues', 'docalist-core')],
    ['mus', '', __('muskogee', 'docalist-core')],
    ['mwl', '', __('mirandais', 'docalist-core')],
    ['mwr', '', __('marvari', 'docalist-core')],
    ['myn', '', __('maya, langues', 'docalist-core')],
    ['myv', '', __('erza', 'docalist-core')],
    ['nah', '', __('nahuatl, langues', 'docalist-core')],
    ['nai', '', __('nord-amérindiennes, langues', 'docalist-core')],
    ['nap', '', __('napolitain', 'docalist-core')],
    ['nau', 'na', __('nauruan', 'docalist-core')],
    ['nav', 'nv', __('navaho', 'docalist-core')],
    ['nbl', 'nr', __('ndébélé du Sud', 'docalist-core')],
    ['nde', 'nd', __('ndébélé du Nord', 'docalist-core')],
    ['ndo', 'ng', __('ndonga', 'docalist-core')],
    ['nds', '', __('allemand, bas', 'docalist-core')],
    ['nds', '', __('bas allemand', 'docalist-core')],
    ['nds', '', __('bas saxon', 'docalist-core')],
    ['nds', '', __('saxon, bas', 'docalist-core')],
    ['nep', 'ne', __('népalais', 'docalist-core')],
    ['new', '', __('nepal bhasa', 'docalist-core')],
    ['new', '', __('newari', 'docalist-core')],
    ['nia', '', __('nias', 'docalist-core')],
    ['nic', '', __('nigéro-kordofaniennes, langues', 'docalist-core')],
    ['niu', '', __('niué', 'docalist-core')],
    ['nno', 'nn', __('norvégien nynorsk', 'docalist-core')],
    ['nno', 'nn', __('nynorsk, norvégien', 'docalist-core')],
    ['nob', 'nb', __('bokmål, norvégien', 'docalist-core')],
    ['nob', 'nb', __('norvégien bokmål', 'docalist-core')],
    ['nog', '', __('nogaï', 'docalist-core')],
    ['nog', '', __('nogay', 'docalist-core')],
    ['non', '', __('norrois, vieux', 'docalist-core')],
    ['nor', 'no', __('norvégien', 'docalist-core')],
    ['nqo', '', __('n\'ko', 'docalist-core')],
    ['nso', '', __('pedi', 'docalist-core')],
    ['nso', '', __('sepedi', 'docalist-core')],
    ['nso', '', __('sotho du Nord', 'docalist-core')],
    ['nub', '', __('nubiennes, langues', 'docalist-core')],
    ['nwc', '', __('newari classique', 'docalist-core')],
    ['nya', 'ny', __('chewa', 'docalist-core')],
    ['nya', 'ny', __('chichewa', 'docalist-core')],
    ['nya', 'ny', __('nyanja', 'docalist-core')],
    ['nym', '', __('nyamwezi', 'docalist-core')],
    ['nyn', '', __('nyankolé', 'docalist-core')],
    ['nyo', '', __('nyoro', 'docalist-core')],
    ['nzi', '', __('nzema', 'docalist-core')],
    ['oci', 'oc', __('occitan (après 1500)', 'docalist-core')],
    ['oji', 'oj', __('ojibwa', 'docalist-core')],
    ['ori', 'or', __('oriya', 'docalist-core')],
    ['orm', 'om', __('galla', 'docalist-core')],
    ['osa', '', __('osage', 'docalist-core')],
    ['oss', 'os', __('ossète', 'docalist-core')],
    ['ota', '', __('turc ottoman (1500-1928)', 'docalist-core')],
    ['oto', '', __('otomi, langues', 'docalist-core')],
    ['paa', '', __('papoues, langues', 'docalist-core')],
    ['pag', '', __('pangasinan', 'docalist-core')],
    ['pal', '', __('pahlavi', 'docalist-core')],
    ['pam', '', __('pampangan', 'docalist-core')],
    ['pan', 'pa', __('pendjabi', 'docalist-core')],
    ['pap', '', __('papiamento', 'docalist-core')],
    ['pau', '', __('palau', 'docalist-core')],
    ['peo', '', __('perse, vieux (ca. 600-400 av. J.-C.)', 'docalist-core')],
    ['per', 'fa', __('persan', 'docalist-core')],
    ['phi', '', __('philippines, langues', 'docalist-core')],
    ['phn', '', __('phénicien', 'docalist-core')],
    ['pli', 'pi', __('pali', 'docalist-core')],
    ['pol', 'pl', __('polonais', 'docalist-core')],
    ['pon', '', __('pohnpei', 'docalist-core')],
    ['por', 'pt', __('portugais', 'docalist-core')],
    ['pra', '', __('prâkrit, langues', 'docalist-core')],
    ['pro', '', __('occitan ancien (jusqu\'à 1500)', 'docalist-core')],
    ['pro', '', __('provençal ancien (jusqu\'à 1500)', 'docalist-core')],
    ['pus', 'ps', __('pachto', 'docalist-core')],
    ['qaa', '', __('réservée à l\'usage local', 'docalist-core')],
    ['que', 'qu', __('quechua', 'docalist-core')],
    ['raj', '', __('rajasthani', 'docalist-core')],
    ['rap', '', __('rapanui', 'docalist-core')],
    ['rar', '', __('maori des îles Cook', 'docalist-core')],
    ['rar', '', __('rarotonga', 'docalist-core')],
    ['roa', '', __('romanes, langues', 'docalist-core')],
    ['roh', 'rm', __('romanche', 'docalist-core')],
    ['rom', '', __('tsigane', 'docalist-core')],
    ['rum', 'ro', __('moldave', 'docalist-core')],
    ['rum', 'ro', __('roumain', 'docalist-core')],
    ['run', 'rn', __('rundi', 'docalist-core')],
    ['rup', '', __('aroumain', 'docalist-core')],
    ['rup', '', __('macédo-roumain', 'docalist-core')],
    ['rus', 'ru', __('russe', 'docalist-core')],
    ['sad', '', __('sandawe', 'docalist-core')],
    ['sag', 'sg', __('sango', 'docalist-core')],
    ['sah', '', __('iakoute', 'docalist-core')],
    ['sai', '', __('sud-amérindiennes, langues', 'docalist-core')],
    ['sal', '', __('salishennes, langues', 'docalist-core')],
    ['sam', '', __('samaritain', 'docalist-core')],
    ['san', 'sa', __('sanskrit', 'docalist-core')],
    ['sas', '', __('sasak', 'docalist-core')],
    ['sat', '', __('santal', 'docalist-core')],
    ['scn', '', __('sicilien', 'docalist-core')],
    ['sco', '', __('écossais', 'docalist-core')],
    ['sel', '', __('selkoupe', 'docalist-core')],
    ['sem', '', __('sémitiques, langues', 'docalist-core')],
    ['sga', '', __('irlandais ancien (jusqu\'à 900)', 'docalist-core')],
    ['sgn', '', __('langues des signes', 'docalist-core')],
    ['shn', '', __('chan', 'docalist-core')],
    ['sid', '', __('sidamo', 'docalist-core')],
    ['sin', 'si', __('singhalais', 'docalist-core')],
    ['sio', '', __('sioux, langues', 'docalist-core')],
    ['sit', '', __('sino-tibétaines, langues', 'docalist-core')],
    ['sla', '', __('slaves, langues', 'docalist-core')],
    ['slo', 'sk', __('slovaque', 'docalist-core')],
    ['slv', 'sl', __('slovène', 'docalist-core')],
    ['sma', '', __('sami du Sud', 'docalist-core')],
    ['sme', 'se', __('sami du Nord', 'docalist-core')],
    ['smi', '', __('sames, langues', 'docalist-core')],
    ['smj', '', __('sami de Lule', 'docalist-core')],
    ['smn', '', __('sami d\'Inari', 'docalist-core')],
    ['smo', 'sm', __('samoan', 'docalist-core')],
    ['sms', '', __('sami skolt', 'docalist-core')],
    ['sna', 'sn', __('shona', 'docalist-core')],
    ['snd', 'sd', __('sindhi', 'docalist-core')],
    ['snk', '', __('soninké', 'docalist-core')],
    ['sog', '', __('sogdien', 'docalist-core')],
    ['som', 'so', __('somali', 'docalist-core')],
    ['son', '', __('songhai, langues', 'docalist-core')],
    ['sot', 'st', __('sotho du Sud', 'docalist-core')],
    ['spa', 'es', __('castillan', 'docalist-core')],
    ['spa', 'es', __('espagnol', 'docalist-core')],
    ['srd', 'sc', __('sarde', 'docalist-core')],
    ['srn', '', __('sranan tongo', 'docalist-core')],
    ['srp', 'sr', __('serbe', 'docalist-core')],
    ['srr', '', __('sérère', 'docalist-core')],
    ['ssa', '', __('nilo-sahariennes, langues', 'docalist-core')],
    ['ssw', 'ss', __('swati', 'docalist-core')],
    ['suk', '', __('sukuma', 'docalist-core')],
    ['sun', 'su', __('soundanais', 'docalist-core')],
    ['sus', '', __('soussou', 'docalist-core')],
    ['sux', '', __('sumérien', 'docalist-core')],
    ['swa', 'sw', __('swahili', 'docalist-core')],
    ['swe', 'sv', __('suédois', 'docalist-core')],
    ['syc', '', __('syriaque classique', 'docalist-core')],
    ['syr', '', __('syriaque', 'docalist-core')],
    ['tah', 'ty', __('tahitien', 'docalist-core')],
    ['tai', '', __('tai, langues', 'docalist-core')],
    ['tam', 'ta', __('tamoul', 'docalist-core')],
    ['tat', 'tt', __('tatar', 'docalist-core')],
    ['tel', 'te', __('télougou', 'docalist-core')],
    ['tem', '', __('temne', 'docalist-core')],
    ['ter', '', __('tereno', 'docalist-core')],
    ['tet', '', __('tetum', 'docalist-core')],
    ['tgk', 'tg', __('tadjik', 'docalist-core')],
    ['tgl', 'tl', __('tagalog', 'docalist-core')],
    ['tha', 'th', __('thaï', 'docalist-core')],
    ['tib', 'bo', __('tibétain', 'docalist-core')],
    ['tig', '', __('tigré', 'docalist-core')],
    ['tir', 'ti', __('tigrigna', 'docalist-core')],
    ['tiv', '', __('tiv', 'docalist-core')],
    ['tkl', '', __('tokelau', 'docalist-core')],
    ['tlh', '', __('klingon', 'docalist-core')],
    ['tli', '', __('tlingit', 'docalist-core')],
    ['tmh', '', __('tamacheq', 'docalist-core')],
    ['tog', '', __('tonga (Nyasa)', 'docalist-core')],
    ['ton', 'to', __('tongan (Îles Tonga)', 'docalist-core')],
    ['tpi', '', __('tok pisin', 'docalist-core')],
    ['tsi', '', __('tsimshian', 'docalist-core')],
    ['tsn', 'tn', __('tswana', 'docalist-core')],
    ['tso', 'ts', __('tsonga', 'docalist-core')],
    ['tuk', 'tk', __('turkmène', 'docalist-core')],
    ['tum', '', __('tumbuka', 'docalist-core')],
    ['tup', '', __('tupi, langues', 'docalist-core')],
    ['tur', 'tr', __('turc', 'docalist-core')],
    ['tut', '', __('altaïques, langues', 'docalist-core')],
    ['tvl', '', __('tuvalu', 'docalist-core')],
    ['twi', 'tw', __('twi', 'docalist-core')],
    ['tyv', '', __('touva', 'docalist-core')],
    ['udm', '', __('oudmourte', 'docalist-core')],
    ['uga', '', __('ougaritique', 'docalist-core')],
    ['uig', 'ug', __('ouïgour', 'docalist-core')],
    ['ukr', 'uk', __('ukrainien', 'docalist-core')],
    ['umb', '', __('umbundu', 'docalist-core')],
    ['und', '', __('indéterminée', 'docalist-core')],
    ['urd', 'ur', __('ourdou', 'docalist-core')],
    ['uzb', 'uz', __('ouszbek', 'docalist-core')],
    ['vai', '', __('vaï', 'docalist-core')],
    ['ven', 've', __('venda', 'docalist-core')],
    ['vie', 'vi', __('vietnamien', 'docalist-core')],
    ['vol', 'vo', __('volapük', 'docalist-core')],
    ['vot', '', __('vote', 'docalist-core')],
    ['wak', '', __('wakashanes, langues', 'docalist-core')],
    ['wal', '', __('wolaitta', 'docalist-core')],
    ['wal', '', __('wolaytta', 'docalist-core')],
    ['war', '', __('waray', 'docalist-core')],
    ['was', '', __('washo', 'docalist-core')],
    ['wel', 'cy', __('gallois', 'docalist-core')],
    ['wen', '', __('sorabes, langues', 'docalist-core')],
    ['wln', 'wa', __('wallon', 'docalist-core')],
    ['wol', 'wo', __('wolof', 'docalist-core')],
    ['xal', '', __('kalmouk', 'docalist-core')],
    ['xal', '', __('oïrat', 'docalist-core')],
    ['xho', 'xh', __('xhosa', 'docalist-core')],
    ['yao', '', __('yao', 'docalist-core')],
    ['yap', '', __('yapois', 'docalist-core')],
    ['yid', 'yi', __('yiddish', 'docalist-core')],
    ['yor', 'yo', __('yoruba', 'docalist-core')],
    ['ypk', '', __('yupik, langues', 'docalist-core')],
    ['zap', '', __('zapotèque', 'docalist-core')],
    ['zbl', '', __('Bliss', 'docalist-core')],
    ['zbl', '', __('symboles Bliss', 'docalist-core')],
    ['zen', '', __('zenaga', 'docalist-core')],
    ['zgh', '', __('amazighe standard marocain', 'docalist-core')],
    ['zha', 'za', __('chuang', 'docalist-core')],
    ['zha', 'za', __('zhuang', 'docalist-core')],
    ['znd', '', __('zandé, langues', 'docalist-core')],
    ['zul', 'zu', __('zoulou', 'docalist-core')],
    ['zun', '', __('zuni', 'docalist-core')],
    ['zxx', '', __('non applicable', 'docalist-core')],
    ['zxx', '', __('pas de contenu linguistique', 'docalist-core')],
    ['zza', '', __('dimili', 'docalist-core')],
    ['zza', '', __('dimli', 'docalist-core')],
    ['zza', '', __('kirdki', 'docalist-core')],
    ['zza', '', __('kirmanjki', 'docalist-core')],
    ['zza', '', __('zaza', 'docalist-core')],
    ['zza', '', __('zazaki', 'docalist-core')],
];